# Generated by Django 4.0.2 on 2022-05-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listtodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Items',
        ),
    ]
